spring:
  application:
    name: woodpecker-back

  datasource:
    url: ${WOODPECKER_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${WOODPECKER_DB_USERNAME}
    password: ${WOODPECKER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      locations: classpath:graphql/**/

logging:
  level:
    org:
      springframework:
        security:
          DEBUG